apiVersion: v1
kind: Service
metadata:
  name: docker-registry-frontend
spec:
  selector:
    app: docker-registry-frontend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-frontend
  labels:
    app: docker-registry-frontend
spec:
  selector:
    matchLabels:
      app: docker-registry-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry-frontend
    spec:
      containers:
      - name: docker-registry-frontend
        image: konradkleine/docker-registry-frontend:v2 
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
#          limits:
#            cpu: 200m
#            memory: 300Mi
        ports:
        - containerPort: 80
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          # value: "docker-registry.default.svc.cluster.local"
          value: "10.102.99.75"
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000"
        - name: ENV_MODE_BROWSE_ONLY
          value: "false"
